name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - flake8
  - pytest
  - scipy
  - matplotlib
  - xarray
  - xmitgcm
  - xgcm
  - cartopy
  - tabulate
  - typing
