"""
Fig. 9 (revised) -- p_atm uncertainty, adjustments, and attribution.

Layout (see smartosse-manuscript/reviews/fig_revision_plan_reviewer2.md for
the original comments-2/3 plan; the 2x2 shape below is a 2026-07-13 redesign
per Matt's request, not yet reflected in that doc -- see STATUS.md):

    2x2 grid:
        (a) sigma_patm STD    (sub-daily std, the main-run prior)    [map + cable]
        (b) sigma_patm SPREAD (Chaudhuri reanalysis spread)          [map + cable]
        (c) all 4 partial cables' |dp_atm| time series, ONE shared axes
            -- color = cable (matches (a)/(b)'s map-dot colors), solid=STD/
            dashed=SPREAD, ONE shared +/-sigma_spread band + ONE P&D 2003
            line (both basin-wide references, un-colored). Cable identity is
            a direct end-of-line label (decluttered so it doesn't collide
            where the 4 cables' curves converge, e.g. the late-Jan spike),
            not an 8-entry legend -- see plot_patm_adjustment_combined().
        (d) per-cable relcon, grouped/shaded/hatched bars, one x-tick per
            cable -- color = cable identity via a 3-shade palette of that
            cable's base color (light=other, mid=winds [=the unmodified base
            color], dark=patm -- patm darkest since it's the headline
            result); hatch (not color) distinguishes STD (plain) vs SPREAD
            (hatched), since color is already spoken for by cable+component.
            See region_group_colors()/plot_relcon_bars_grouped().

    The old 4-panels-per-row layout (one timeseries + one relcon-bar-pair per
    cable, 8 panels total under (a)/(b)) is retained as
    plot_patm_adjustment_row()/plot_relcon_bars_row() (still correct, just
    unused by make_fig9() now) -- useful again if the merged (c)/(d) panels
    ever read as too cluttered and we want to fall back.

Everything here is a small function taking already-loaded data (or a run
directory) and returning ``ax`` (or ``fig, ax``) so panels can be built,
tweaked, and re-laid-out interactively from a notebook. Spatial panels follow
the smartosse.plot conventions (``spna``); panels (a)/(b) plot lat/lon fields
directly (contourf + PlateCarree) rather than via ``ds.plotpc``.

NOTE (panel a/b source data): the ASTE-gridded `wApressure_*.bin` weight
files (`w = sigma^-2`, regridded onto the ASTE grid via MITgcm's EXF) are
what actually get fed into the OSSEs as control-uncertainty priors, but they
don't make good plots. Panels (a)/(b) instead use
`sigma_patm_{std,spread}_2012.nc` under `figures/data/`, generated by
`gen_patm_uncertainty_fields.py` directly from the JRA55/JRA3Q/ERA5
reanalysis products (see that script's docstring for the recipe, and for a
real lon-alignment bug it found and fixed along the way). Regenerate those
.nc files with:
    conda activate /work/08381/goldberg/ls6/miniforge3/envs/esmpy_3.10
    python -m smartosse.figures.gen_patm_uncertainty_fields
load_sigma_patm_std/_spread() (ASTE grid, from the weight binaries) are still
used for row 2's grey band, which needs to index sigma at cable (tile, j, i)
sensor locations.

NOTE (data availability): the FM run directories below live on
/scratch/08381/goldberg/aste_270x450x180/osses/. Some iter0000/ dirs and
xx_apressure.effective / data.ecco / data.ctrl files were missing on this
machine as of 2026-07-12 (likely not yet copied over) -- see the loader
docstrings for what each function needs.

NOTE (P&D 2003 anchor): we don't have the actual Ponte & Dorandeau (2003)
data; per Matt's estimate the SPNA value is roughly 4 hPa^2 (a mean-square
DIFFERENCE between reanalysis products, hence squared units), so the RMS
anchor plotted on the [hPa] row-2 axes is sqrt(4) = 2 hPa. Treat PD_2003_RMS_HPA
as a rough placeholder, not a citation-grade number.

NOTE (xx_apressure time ordering): load_patm_adjustment reproduces a time
reversal applied in patm.ipynb (``.sel(time=slice(None, None, -1))``) before
stamping calendar dates onto the control knots. That was empirically
necessary there but not independently re-derived here -- if a returned series
looks calendar-inverted, try ``reverse_time=False``. For a first-principles
control<->diagnostic time alignment (recommended for anything quantitative,
e.g. slope fits), see eta_ib_histogram.py's ctrl_t/diag_t interpolation
instead.
"""
import os
import glob

import numpy as np
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as ticker
import matplotlib.colors as mcolors
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
import cartopy.crs as ccrs

from ..utils import read_aste_bin
from ..plot import spna
from .figs_utils import add_panel_label, latex_escape

# -----------------------------------------------------------------------------
# Defaults -- override any of these via function kwargs; nothing here is load-
# bearing inside the plotting functions themselves.
# -----------------------------------------------------------------------------

WEIGHT_DIR = '/work2/08381/goldberg/ls6/aste_270x450x180/run_template/input_weight/'
SIGMA_STD_FNAME = 'wApressure_ASTE270_EXFpress_std_new.bin'       # sub-daily std prior (main run)
SIGMA_SPREAD_FNAME = 'wApressure_ASTE270_jra55_jra3q_era_spread.bin'  # Chaudhuri reanalysis-spread prior

# Lat/lon (JRA55-grid) versions of the same two fields, generated by
# gen_patm_uncertainty_fields.py -- these are what panels (a)/(b) actually
# plot. The ASTE-gridded weight binaries above are what's fed into the OSSEs
# as control-uncertainty priors, but they don't make good plots (regridding
# artifacts); load_sigma_patm_std/_spread (ASTE grid, above) are kept around
# only for compute_sigma_band_hpa, which needs to index the SPREAD field at
# cable sensor (tile, j, i) locations for row 2's grey band.
FIELDS_DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
SIGMA_STD_NC = os.path.join(FIELDS_DATA_DIR, 'sigma_patm_std_2012.nc')
SIGMA_SPREAD_NC = os.path.join(FIELDS_DATA_DIR, 'sigma_patm_spread_2012.nc')

DATA_CTRL_DIR_STD = WEIGHT_DIR + 'data_ctrl_dir_std/'
DATA_CTRL_DIR_SPREAD = WEIGHT_DIR + 'data_ctrl_dir_spread/'

RUN_DIR_ROOT_STD = '/scratch/08381/goldberg/aste_270x450x180/osses/runc68v_froman_partialcables_jrastd/201201/'
RUN_DIR_ROOT_SPREAD = '/scratch/08381/goldberg/aste_270x450x180/osses/runc68v_froman_partialcables_jraspread/201201/'

BP_DATA_DIR = '/work2/08381/goldberg/ls6/aste_270x450x180/run_template/input_ecco/smart_phibot/one_month_daily_bp_experiments/'
BP_FNAME_PATTERN = 'SMART_bp_detide16constituents_detrend_{mo_str}_31x1350x270*_{region}.bin'

# row-2 order == (c),(d),(e),(f) in the plan sketch
REGIONS = ['labsea', 'subgyre', 'northsea', 'newfoundland']
REGION_LABELS = {'labsea': 'LS', 'subgyre': 'SPG', 'northsea': 'NS', 'newfoundland': 'Nfl'}
REGION_COLORS = {
    'newfoundland': '#82D173',
    'labsea': '#1b98e0',
    'subgyre': '#fb8b24',
    'northsea': '#820263',
}

RELCON_GROUP_COLORS = {'winds': '#bcbddc', 'patm': '#807dba', 'other': '#3f007d'}  # ColorBrewer Purples -- kept for plot_relcon_bars/plot_relcon_bars_region (unused by make_fig9() now, see panel (d))
RELCON_GROUP_ORDER = ('other', 'winds', 'patm')  # stacking order, bottom -> top
# Display labels for the relcon group legend -- patm rendered as math so it
# matches the $p_{\mathrm{atm}}$ notation used elsewhere (e.g. SIGMA_BAND_LABEL).
RELCON_GROUP_LABELS = {'winds': 'winds', 'patm': r'$p_{\mathrm{atm}}$', 'other': 'other'}

# Panel (d): per-cable shade palette. 'winds' -> factor 0 (the cable's own
# unmodified color, i.e. the same swatch as the (a)/(b) map dots and panel
# (c)'s lines); 'other' lightened, 'patm' darkened (darkest, since it's the
# headline result) -- see _shade_color()/region_group_colors().
REGION_SHADE_FACTORS = {'other': 0.6, 'winds': 0.0, 'patm': -0.35}


def _shade_color(color, factor):
    """Lighten (factor>0) or darken (factor<0) `color` by mixing toward white/black.

    `factor` in [-1, 1]; 0 returns `color` unchanged. Used to derive panel
    (d)'s per-cable light/medium/dark palette from each cable's single base
    color (REGION_COLORS) rather than hand-picking 12 colors.
    """
    rgb = np.array(mcolors.to_rgb(color))
    target = np.ones(3) if factor >= 0 else np.zeros(3)
    return tuple(np.clip(rgb + (target - rgb) * abs(factor), 0., 1.))


def region_group_colors(region, region_colors=None, shade_factors=None):
    """{'other': light, 'winds': medium, 'patm': dark} shades of one cable's base color.

    Powers panel (d)'s bars, so that cable identity (color) and control-group
    identity (shade) are both legible at once without a 12-entry legend --
    only the shade meaning (light/mid/dark) needs explaining, once, in
    neutral grey (see _relcon_shade_legend_handles()).
    """
    region_colors = region_colors or REGION_COLORS
    shade_factors = shade_factors or REGION_SHADE_FACTORS
    base = region_colors[region]
    return {g: _shade_color(base, shade_factors[g]) for g in RELCON_GROUP_ORDER}

PD_2003_MSD_HPA2 = 4.0                    # Matt's rough SPNA estimate (mean-square diff, hPa^2)
PD_2003_RMS_HPA = float(np.sqrt(PD_2003_MSD_HPA2))  # ~2 hPa; what actually gets plotted on [hPa] axes

# Row-2 line styles, shared between plot_patm_adjustment_timeseries (the
# actual per-panel colored lines) and _row2_legend_handles (the black-only
# legend swatches) so the two can't drift apart.
STD_LINE_STYLE = dict(ls='-')
SPREAD_LINE_STYLE = dict(ls='--')            # was ':' -- now "the density P&D used to have"
PD_LINE_STYLE = dict(ls=(0, (1, 1)), lw=1.8)  # densely dotted, black, a bit thicker than before
SIGMA_BAND_LABEL = r'$\pm\sigma_{p_{\mathrm{atm}}}^{\mathrm{spread}}$'


# =============================================================================
# Loaders
# =============================================================================

def load_sigma_patm(fname, weight_dir=WEIGHT_DIR):
    """ASTE-gridded p_atm uncertainty sigma [Pa] from a `w = sigma^-2` weight binary.

    Works for either prior -- pass SIGMA_STD_FNAME or SIGMA_SPREAD_FNAME (or
    any other wApressure_*.bin living in weight_dir).
    """
    w = read_aste_bin(os.path.join(weight_dir, fname))
    sigma = w ** -0.5
    return sigma.where(np.isfinite(sigma))  # Pa, land/zero-weight -> NaN


def load_sigma_patm_std(weight_dir=WEIGHT_DIR, fname=SIGMA_STD_FNAME):
    return load_sigma_patm(fname, weight_dir=weight_dir)


def load_sigma_patm_spread(weight_dir=WEIGHT_DIR, fname=SIGMA_SPREAD_FNAME):
    return load_sigma_patm(fname, weight_dir=weight_dir)


def load_sigma_patm_std_map(nc_path=SIGMA_STD_NC):
    """sigma_patm STD [Pa], lat/lon (JRA55 grid) -- for panel (a)'s map.

    From gen_patm_uncertainty_fields.py's compute_sigma_std(): sub-daily std
    of JRA55 p_atm, time-mean over the year. Unlike load_sigma_patm_std()
    (ASTE grid, from the model's own weight binary), this is meant to be
    plotted directly.
    """
    return xr.open_dataarray(nc_path)


def load_sigma_patm_spread_map(nc_path=SIGMA_SPREAD_NC):
    """sigma_patm SPREAD [Pa], lat/lon (JRA55 grid) -- for panel (b)'s map.

    From gen_patm_uncertainty_fields.py's compute_sigma_spread(): max-over-
    pairs temporal std of JRA55/JRA3Q/ERA5 p_atm differences (Chaudhuri).
    """
    return xr.open_dataarray(nc_path)


def get_cable_sensor_args(region, mo_str='201201', bp_dir=BP_DATA_DIR, nz=None):
    """tile/j/i sensor indices (dims='sensor') for one partial cable's synthetic bp file.

    Matches on `*_<region>.bin` (leading underscore) rather than `*<region>.bin`
    -- the latter also matches e.g. "..._allbutnorthsea.bin" for region="northsea".
    """
    pattern = os.path.join(bp_dir, BP_FNAME_PATTERN.format(mo_str=mo_str, region=region))
    matches = glob.glob(pattern)
    if not matches:
        raise FileNotFoundError(f'No SMART bp file found for region={region!r} matching {pattern}')
    if len(matches) > 1:
        raise ValueError(f'Ambiguous match for region={region!r}: {matches}')

    bp = read_aste_bin(matches[0], nz=nz)
    bp = bp.where(bp != -9999., 0.)
    tile, j, i = np.where((bp[0] != 0.) & (~np.isnan(bp[0])))
    return dict(
        tile=xr.DataArray(tile, dims='sensor'),
        j=xr.DataArray(j, dims='sensor'),
        i=xr.DataArray(i, dims='sensor'),
    )


def get_cable_lonlat(ds, sensor_args):
    """(lons, lats) at a cable's sensor locations, from the grid dataset."""
    return ds.XC.isel(**sensor_args).values, ds.YC.isel(**sensor_args).values


def load_patm_adjustment(run_dir_root, region, iternum=20, datetimes=None, reverse_time=True):
    """xx_apressure.effective control-adjustment knots [Pa] for one partial-cable run.

    Returns a DataArray with dims (time, tile, j, i). See the module docstring
    re: `reverse_time`.
    """
    fname = f'{run_dir_root}/{region}/iter{iternum:04d}/xx_apressure.effective.{iternum:010d}.data'
    xx = read_aste_bin(fname)
    xx = xx.rename({'k': 'time'})

    if datetimes is not None:
        nt = len(datetimes)
        xx = xx.isel(time=slice(0, nt))
        if reverse_time:
            xx = xx.isel(time=slice(None, None, -1))
        xx = xx.assign_coords(time=('time', pd.DatetimeIndex(datetimes)))
    return xx  # Pa


def _group_ctrl(da):
    """Collapse a `ctrl` coordinate (xx_uwind, xx_vwind, xx_apressure, ...) into
    winds / patm / other groups and sum over it."""
    group = xr.DataArray(
        np.select(
            [da.ctrl.isin(['xx_uwind', 'xx_vwind']), da.ctrl == 'xx_apressure'],
            ['winds', 'patm'],
            default='other',
        ),
        dims='ctrl',
        coords={'ctrl': da.ctrl},
        name='group',
    )
    return da.groupby(group).sum(dim='ctrl')


def load_relcon_grouped(run_dir, iternum=20, data_ctrl_dir=None, weight_dir=WEIGHT_DIR, nx=270):
    """Time-mean relative control contribution for one run dir, grouped winds/patm/other.

    Requires the `smartuq` package (ControlDataset). Returns an xr.DataArray
    with a single 'group' dim, summing to 1.
    """
    from smartuq.ctrl import ControlDataset

    cds = ControlDataset(
        f'{run_dir.rstrip("/")}/iter{iternum:04d}/',
        data_ctrl_dir=data_ctrl_dir,
        weight_dir=weight_dir,
        backend='aste',
        nx=nx,
        iternum=iternum,
    )
    return _group_ctrl(cds.ds.std_cost.mean('time'))


def load_relcon_std_spread(
    run_dir_root_std=RUN_DIR_ROOT_STD,
    run_dir_root_spread=RUN_DIR_ROOT_SPREAD,
    regions=REGIONS,
    iternum=20,
    weight_dir=WEIGHT_DIR,
    data_ctrl_dir_std=DATA_CTRL_DIR_STD,
    data_ctrl_dir_spread=DATA_CTRL_DIR_SPREAD,
):
    """Mean-over-region, time-mean relcon for the STD and SPREAD runs.

    Returns {'std': DataArray[group], 'spread': DataArray[group]}, each summing
    to 1 across 'group' (winds/patm/other). NB: std and spread runs use
    *different* data_ctrl_dir (their data.ctrl files point at different
    xx_apressure weight files) -- don't share one data_ctrl_dir across both.

    Backed the old single-mean "(g)" panel (plot_relcon_bars), now unused in
    make_fig9() in favor of the per-region row-3 bars (load_relcon_per_region
    / plot_relcon_bars_region) -- kept in case a basin-mean summary is useful
    again later.
    """
    configs = {'std': (run_dir_root_std, data_ctrl_dir_std),
               'spread': (run_dir_root_spread, data_ctrl_dir_spread)}
    out = {}
    for run_name, (root, ctrl_dir) in configs.items():
        per_region = [
            load_relcon_grouped(f'{root}/{region}/', iternum=iternum,
                                 data_ctrl_dir=ctrl_dir, weight_dir=weight_dir)
            for region in regions
        ]
        out[run_name] = xr.concat(
            per_region, dim=xr.DataArray(regions, dims='region')
        ).mean('region')
    return out


def load_relcon_per_region(
    run_dir_root_std=RUN_DIR_ROOT_STD,
    run_dir_root_spread=RUN_DIR_ROOT_SPREAD,
    regions=REGIONS,
    iternum=20,
    weight_dir=WEIGHT_DIR,
    data_ctrl_dir_std=DATA_CTRL_DIR_STD,
    data_ctrl_dir_spread=DATA_CTRL_DIR_SPREAD,
):
    """Per-region (not averaged), time-mean relcon for the STD and SPREAD
    runs -> row 3's per-cable bar pairs.

    Returns {'std': {region: DataArray[group]}, 'spread': {region:
    DataArray[group]}} -- same per-region values load_relcon_std_spread()
    averages away with .mean('region').
    """
    configs = {'std': (run_dir_root_std, data_ctrl_dir_std),
               'spread': (run_dir_root_spread, data_ctrl_dir_spread)}
    out = {}
    for run_name, (root, ctrl_dir) in configs.items():
        out[run_name] = {
            region: load_relcon_grouped(f'{root}/{region}/', iternum=iternum,
                                         data_ctrl_dir=ctrl_dir, weight_dir=weight_dir)
            for region in regions
        }
    return out


def compute_sigma_band_hpa(sigma_spread, sensor_args):
    """Scalar plausibility half-width [hPa] for one cable: mean SPREAD sigma
    across that cable's sensors."""
    return float(sigma_spread.isel(**sensor_args).mean()) / 100.


def load_row2_data(
    ds,
    sigma_spread,
    regions=REGIONS,
    mo_str='201201',
    iternum=20,
    run_dir_root_std=RUN_DIR_ROOT_STD,
    run_dir_root_spread=RUN_DIR_ROOT_SPREAD,
    bp_dir=BP_DATA_DIR,
    reverse_time=True,
):
    """Bundle everything plot_patm_adjustment_row() needs, per region.

    Returns {region: {'time', 'adj_std', 'adj_spread', 'sigma_band_hpa',
    'lons', 'lats'}}.
    """
    start = pd.to_datetime(mo_str, format='%Y%m')
    end = start + pd.offsets.MonthEnd(1)
    datetimes = pd.date_range(start=start, end=end, freq='D')

    out = {}
    for region in regions:
        sensor_args = get_cable_sensor_args(region, mo_str=mo_str, bp_dir=bp_dir, nz=len(datetimes))
        lons, lats = get_cable_lonlat(ds, sensor_args)

        adj_std = load_patm_adjustment(run_dir_root_std, region, iternum=iternum,
                                        datetimes=datetimes, reverse_time=reverse_time)
        adj_spread = load_patm_adjustment(run_dir_root_spread, region, iternum=iternum,
                                           datetimes=datetimes, reverse_time=reverse_time)

        out[region] = dict(
            time=datetimes,
            adj_std=adj_std.isel(**sensor_args),      # (time, sensor), Pa
            adj_spread=adj_spread.isel(**sensor_args),
            sigma_band_hpa=compute_sigma_band_hpa(sigma_spread, sensor_args),
            lons=lons,
            lats=lats,
        )
    return out


# =============================================================================
# Plotting primitives -- each takes/returns `ax` so panels can be composed and
# customized freely from a notebook.
# =============================================================================

def plot_sigma_patm_map(
    sigma,
    ax=None,
    cable_lonlat=None,     # dict[region] -> (lons, lats); omit to skip cable overlay
    region_colors=None,
    cmap='Greys',
    hpa=True,
    add_colorbar=True,
    cbar_kwargs=None,
    scatter_kwargs=None,
    **contourf_kwargs,
):
    """sigma_patm map on the SPNA projection, optionally with per-region cable markers.

    `sigma` is a lat/lon (JRA55-grid) DataArray in Pa, e.g. from
    load_sigma_patm_std_map()/load_sigma_patm_spread_map() -- these are
    plotted directly (xarray contourf + PlateCarree transform), unlike the
    ASTE-gridded weight-derived fields which need `ds.plotpc`. vmin/vmax/
    levels are left to xarray's own robust scaling unless passed via
    contourf_kwargs -- the STD and SPREAD fields differ by ~5-10x in
    magnitude, so a shared hardcoded range would make one panel look empty.
    """
    if ax is None:
        fig, ax = spna()
    else:
        fig = ax.figure

    field = sigma / 100. if hpa else sigma

    ck = dict(cmap=cmap, add_colorbar=False, transform=ccrs.PlateCarree(), robust=True)
    ck.update(contourf_kwargs)
    p = field.plot.contourf(ax=ax, **ck)

    cb = None
    if add_colorbar:
        cbk = dict(orientation='horizontal', shrink=0.8, pad=0.05)
        cbk.update(cbar_kwargs or {})
        cb = fig.colorbar(p, ax=ax, **cbk)
        cb.ax.set_xlabel('[hPa]' if hpa else '[Pa]', fontsize=16)

    if cable_lonlat is not None:
        region_colors = region_colors or REGION_COLORS
        sk = dict(s=20, edgecolor='w', linewidth=0.5, transform=ccrs.PlateCarree(), zorder=4)
        sk.update(scatter_kwargs or {})
        for region, (lons, lats) in cable_lonlat.items():
            ax.scatter(lons, lats, facecolor=region_colors.get(region, 'k'), **sk)

    return ax, cb, p


def plot_relcon_bars(
    relcon,
    ax=None,
    colors=None,
    group_order=RELCON_GROUP_ORDER,
    width=0.5,
    legend=True,
    **bar_kwargs,
):
    """Panel (g): stacked relcon bars, one bar per run (dict key), stacked by group.

    `relcon` : dict[str, xr.DataArray] with a 'group' dim (e.g. from
    load_relcon_std_spread()), values summing to ~1 per run.
    """
    if ax is None:
        fig, ax = plt.subplots(figsize=(2.4, 4))
    else:
        fig = ax.figure

    colors = colors or RELCON_GROUP_COLORS
    run_names = list(relcon.keys())
    x = np.arange(len(run_names))

    for xi, run_name in zip(x, run_names):
        bottom = 0.
        da = relcon[run_name]
        for group in group_order:
            val = float(da.sel(group=group))
            ax.bar(xi, val, width, bottom=bottom, color=colors[group],
                   edgecolor='k', linewidth=0.5, **bar_kwargs)
            bottom += val

    ax.set_xticks(x)
    ax.set_xticklabels(run_names)
    ax.set_ylim(0, 1)
    ax.set_ylabel('relative contribution')
    ax.grid(axis='y', alpha=0.3)

    if legend:
        handles = [Patch(facecolor=colors[g], edgecolor='k', label=g) for g in group_order]
        ax.legend(handles=handles, frameon=False, fontsize=9,
                  loc='upper center', bbox_to_anchor=(0.5, -0.12), ncol=1)

    return ax


def plot_relcon_bars_region(
    ax,
    relcon_std,       # DataArray[group], sums to 1
    relcon_spread,    # DataArray[group], sums to 1
    group_order=RELCON_GROUP_ORDER,
    colors=None,
    height=0.6,
    spread_hatch=None,
    tick_fontsize=16,
    ylabel_fontsize=None,
    **barh_kwargs,
):
    """Row 3: one region's STD/SPREAD relcon as a pair of horizontal stacked
    bars (STD above, SPREAD below), winds/patm/other, each summing to 1.

    The y-tick labels ('STD'/'SPREAD') are what distinguish the two rows;
    pass `spread_hatch` (e.g. '///') to also hatch SPREAD if the labels alone
    aren't enough (e.g. grayscale printing, cropped screenshot) -- off by
    default since it's redundant once the labels are legible. `ylabel_fontsize`
    (defaults to `tick_fontsize` if omitted) sets just the STD/SPREAD y-tick
    labels, independent of the x-tick (0/0.5/1) fontsize.
    """
    colors = colors or RELCON_GROUP_COLORS
    ylabel_fontsize = tick_fontsize if ylabel_fontsize is None else ylabel_fontsize

    for y, relcon, hatch in [(1, relcon_std, None), (0, relcon_spread, spread_hatch)]:
        left = 0.
        for group in group_order:
            val = float(relcon.sel(group=group))
            ax.barh(y, val, height=height, left=left, color=colors[group],
                     edgecolor='k', linewidth=0.5, hatch=hatch, **barh_kwargs)
            left += val

    ax.set_xlim(0, 1)
    ax.set_ylim(-0.6, 1.6)
    ax.set_yticks([1, 0])
    ax.set_yticklabels(['STD', 'SPREAD'])
    ax.set_xticks([0, 0.5, 1])
    ax.tick_params(axis='both', labelsize=tick_fontsize)
    ax.tick_params(axis='y', labelsize=ylabel_fontsize, length=0)
    for spine in ('top', 'right'):
        ax.spines[spine].set_visible(False)

    return ax


def plot_relcon_bars_row(axes, relcon_per_region, regions=REGIONS, **region_kwargs):
    """Row 3: call plot_relcon_bars_region() once per cable across `axes`.

    `relcon_per_region` is load_relcon_per_region()'s return value -- {'std':
    {region: DataArray[group]}, 'spread': {region: DataArray[group]}}.
    """
    for ax, region in zip(axes, regions):
        plot_relcon_bars_region(
            ax, relcon_per_region['std'][region], relcon_per_region['spread'][region],
            **region_kwargs,
        )

    for ax in axes[1:]:
        ax.tick_params(labelleft=False)

    return axes


def plot_relcon_bars_grouped(
    ax,
    relcon_per_region,   # {'std': {region: DataArray[group]}, 'spread': {region: DataArray[group]}}
    regions=REGIONS,
    region_labels=None,
    region_colors=None,
    shade_factors=None,
    group_order=RELCON_GROUP_ORDER,
    bar_width=0.32,
    pair_gap=0.04,
    spread_hatch='///',
    tick_fontsize=16,
    ylabel_fontsize=20,
    ylabel='relative contribution',
):
    """Panel (d): grouped STD/SPREAD relcon bars, one x-tick per cable
    (replaces the old row-3 4-panels-of-horizontal-bar-pairs layout).

    Color = cable identity, via region_group_colors()'s light/mid/dark shade
    of that cable's base color for other/winds/patm (dark = patm, the
    headline result) -- reuses the same REGION_COLORS as (a)/(b)/(c), so
    cable identity reads consistently across the whole figure. Hatch (not
    color, which is already spoken for) distinguishes STD (plain) from
    SPREAD (`spread_hatch`) within each cable's pair of bars.
    """
    region_labels = region_labels or REGION_LABELS
    region_colors = region_colors or REGION_COLORS

    x = np.arange(len(regions))
    half_step = (bar_width + pair_gap) / 2.
    std_x = x - half_step
    spread_x = x + half_step

    for xi_std, xi_spread, region in zip(std_x, spread_x, regions):
        colors = region_group_colors(region, region_colors, shade_factors)
        for xi, run_name, hatch in [(xi_std, 'std', None), (xi_spread, 'spread', spread_hatch)]:
            bottom = 0.
            da = relcon_per_region[run_name][region]
            for group in group_order:
                val = float(da.sel(group=group))
                ax.bar(xi, val, bar_width, bottom=bottom, color=colors[group],
                       edgecolor='k', linewidth=0.5, hatch=hatch)
                bottom += val

    ax.set_xticks(x)
    ax.set_xticklabels([latex_escape(f'{region_labels[r]}_cable') for r in regions], fontsize=tick_fontsize)
    ax.set_ylim(0, 1)
    ax.set_yticks([0, 0.5, 1])
    ax.tick_params(axis='y', labelsize=tick_fontsize)
    ax.set_ylabel(ylabel, fontsize=ylabel_fontsize)
    ax.grid(axis='y', alpha=0.3)
    ax.set_axisbelow(True)
    for spine in ('top', 'right'):
        ax.spines[spine].set_visible(False)

    return ax


def _relcon_shade_legend_handles(shade_factors=None, neutral='0.55'):
    """Neutral-grey light/mid/dark swatches explaining panel (d)'s shade
    meaning (other/winds/patm) -- one shared key, since the actual color
    varies per cable."""
    shade_factors = shade_factors or REGION_SHADE_FACTORS
    return [
        Patch(facecolor=_shade_color(neutral, shade_factors[g]), edgecolor='k',
              label=RELCON_GROUP_LABELS[g])
        for g in RELCON_GROUP_ORDER
    ]


def _relcon_hatch_legend_handles(spread_hatch='///'):
    """STD (plain) vs SPREAD (hatched) key for panel (d), in neutral white/grey
    since hatch (not color) is what distinguishes the two there."""
    return [
        Patch(facecolor='w', edgecolor='k', hatch=None, label='STD'),
        Patch(facecolor='w', edgecolor='k', hatch=spread_hatch, label='SPREAD'),
    ]


def _row2_legend_handles(pd_rms_label='P&D 2003\n(SPNA)'):
    """Black-only proxy handles for row 2's STD/SPREAD/P&D/sigma-band legend.

    Built from proxies (not the actual plotted-line artists) so the legend
    swatches are always black, regardless of which region's (colored) panel
    hosts the legend -- otherwise e.g. placing it in the Newfoundland panel
    would render every swatch in Newfoundland's green.
    """
    return [
        Line2D([0], [0], color='k', label='STD', **STD_LINE_STYLE),
        Line2D([0], [0], color='k', label='SPREAD', **SPREAD_LINE_STYLE),
        Line2D([0], [0], color='k', label=latex_escape(pd_rms_label), **PD_LINE_STYLE),
        Patch(facecolor='0.5', alpha=0.3, edgecolor='none', label=SIGMA_BAND_LABEL),
    ]


def _month_day_formatter(x, pos=None):
    return mdates.num2date(x).strftime('%b\n%d')


def _style_time_axis(ax, time, yticks=(0, 1, 2), ylim=None, tick_labelsize=16):
    """Shared x/y-axis finishing for the row-2-style time series panels
    (month/day x ticks over the plotted month, y gridlines only at `yticks`).

    Factored out of plot_patm_adjustment_timeseries() so plot_patm_adjustment_combined()
    (panel (c), all 4 cables on one axes) can't drift out of sync with it.
    """
    ax.set_axisbelow(True)
    t0 = pd.to_datetime(np.asarray(time)[0])
    t1 = t0 + pd.offsets.MonthEnd(0)
    ax.set_xlim(t0, t1)
    ax.xaxis.set_major_formatter(ticker.FuncFormatter(_month_day_formatter))
    ax.tick_params(axis='x', rotation=0, labelsize=tick_labelsize)
    if yticks is not None:
        ax.set_yticks(yticks)   # ylim (incl. any dip below 0) is untouched -- just no tick/gridline there
    if ylim is not None:
        ax.set_ylim(*ylim)
    ax.grid(axis='y')
    ax.grid(axis='x', linestyle='--', alpha=0.5)


def plot_patm_adjustment_timeseries(
    ax,
    time,
    adj_std,          # (time, sensor) or (time,), Pa
    adj_spread,        # same
    sigma_band_hpa,    # scalar half-width [hPa], e.g. from compute_sigma_band_hpa
    pd_rms_hpa=PD_2003_RMS_HPA,
    color='k',
    symmetric_band=True,
    yticks=(0, 1, 2),   # only these get labeled/gridlined; ylim still dips below 0
    ylim=None,          # e.g. (-1, 3) to share one range across all row-2 panels
    tick_labelsize=16,  # x-axis (date) tick label size; every panel has an x-axis
    band_kwargs=None,
    pd_line_kwargs=None,
    std_line_kwargs=None,
    spread_line_kwargs=None,
):
    """One Fig-9 row-2 panel: STD (solid) vs SPREAD (dashed) |dp_atm| against
    the SPREAD-based plausibility band and the P&D 2003 RMS anchor (black,
    densely dotted).
    """
    # this env's matplotlib (3.4.3) predates pandas 2.x dropping `Index[:,
    # None]` -- ax.plot()/fill_between() on a raw pd.DatetimeIndex raises
    # "Multi-dimensional indexing... no longer supported". A plain
    # datetime64 ndarray plots fine either way.
    time = np.asarray(time)
    sensor_dim = 'sensor' if 'sensor' in adj_std.dims else None

    def _mean_abs_hpa(da):
        da = np.abs(da) / 100.
        return da.mean(sensor_dim) if sensor_dim else da

    std_kwargs = dict(color=color, label='STD', **STD_LINE_STYLE)
    std_kwargs.update(std_line_kwargs or {})
    spread_kwargs = dict(color=color, label='SPREAD', **SPREAD_LINE_STYLE)
    spread_kwargs.update(spread_line_kwargs or {})

    ax.plot(time, _mean_abs_hpa(adj_std), **std_kwargs)
    ax.plot(time, _mean_abs_hpa(adj_spread), **spread_kwargs)

    lo = -sigma_band_hpa if symmetric_band else 0.
    bk = dict(color='0.5', alpha=0.3, edgecolor='none', label=SIGMA_BAND_LABEL, zorder=0)
    bk.update(band_kwargs or {})
    ax.fill_between(time, lo, sigma_band_hpa, **bk)

    pk = dict(color='k', label='P&D 2003 (SPNA)', zorder=1, **PD_LINE_STYLE)
    pk.update(pd_line_kwargs or {})
    ax.axhline(pd_rms_hpa, **pk)

    _style_time_axis(ax, time, yticks=yticks, ylim=ylim, tick_labelsize=tick_labelsize)

    return ax


def plot_patm_adjustment_row(axes, row2_data, regions=REGIONS, region_labels=None,
                              region_colors=None, ylabel='[hPa]', **timeseries_kwargs):
    """Row 2: call plot_patm_adjustment_timeseries() once per cable across `axes`."""
    region_labels = region_labels or REGION_LABELS
    region_colors = region_colors or REGION_COLORS

    for ax, region in zip(axes, regions):
        d = row2_data[region]
        plot_patm_adjustment_timeseries(
            ax, d['time'], d['adj_std'], d['adj_spread'], d['sigma_band_hpa'],
            color=region_colors.get(region, 'k'), **timeseries_kwargs,
        )
        # no ax.set_title() -- the region name is folded into the panel
        # letter label instead (add_panel_label(..., suffix=' LS_cable')),
        # done by the caller since it also owns the letters.

    axes[0].set_ylabel(ylabel, fontsize=20)
    axes[0].tick_params(axis='y', labelsize=18)
    for ax in axes[1:]:
        ax.spines['left'].set_visible(False)
        ax.tick_params(labelleft=False)

    return axes


def _declutter_1d(values, min_gap):
    """Nudge `values` upward (preserving rank order) so consecutive sorted
    values are at least `min_gap` apart. Returns an array aligned to the
    *original* (unsorted) order of `values`.

    Used to keep panel (c)'s 4 end-of-line cable labels from overlapping
    where the curves converge (e.g. all 4 cables land within ~0.5 hPa of each
    other during the late-Jan spike, per STATUS.md).
    """
    values = np.asarray(values, dtype=float)
    order = np.argsort(values)
    adjusted = values.copy()
    for k in range(1, len(order)):
        i, prev = order[k], order[k - 1]
        if adjusted[i] - adjusted[prev] < min_gap:
            adjusted[i] = adjusted[prev] + min_gap
    return adjusted


def plot_patm_adjustment_combined(
    ax,
    row2_data,
    regions=REGIONS,
    region_labels=None,
    region_colors=None,
    sigma_band_hpa=None,
    pd_rms_hpa=PD_2003_RMS_HPA,
    yticks=(0, 1, 2),
    ylim=(-1, 3),
    tick_labelsize=16,
    ylabel='[hPa]',
    ylabel_fontsize=20,
    label_fontsize=16,
    min_label_gap=0.18,
    label_x=1.015,
    band_kwargs=None,
    pd_line_kwargs=None,
    std_line_kwargs=None,
    spread_line_kwargs=None,
):
    """Panel (c): all 4 cables' STD (solid) vs SPREAD (dashed) |dp_atm| on one
    shared axes, replacing the old 4-panels-per-region row.

    Color = cable identity (REGION_COLORS, matching (a)/(b)'s map dots and
    panel (d)'s bars). ONE shared +/-sigma_spread band (mean of the 4 cables'
    own bands -- they're all similar magnitude, see STATUS.md) and ONE P&D
    2003 line, both plotted un-colored (grey/black) since they're basin-wide
    references, not specific to any one cable.

    Cable identity is a direct end-of-line label at the STD curve's last
    value (decluttered via _declutter_1d so 4 converging curves don't
    overlap) rather than an 8-entry (4 cable x 2 linestyle) legend -- pass
    a separate small legend (e.g. _row2_legend_handles()) for the
    STD/SPREAD/band/P&D linestyle key, which is cable-agnostic.
    """
    region_labels = region_labels or REGION_LABELS
    region_colors = region_colors or REGION_COLORS

    time = np.asarray(row2_data[regions[0]]['time'])

    if sigma_band_hpa is None:
        sigma_band_hpa = float(np.mean([row2_data[r]['sigma_band_hpa'] for r in regions]))

    std_kwargs_base = dict(**STD_LINE_STYLE)
    std_kwargs_base.update(std_line_kwargs or {})
    spread_kwargs_base = dict(**SPREAD_LINE_STYLE)
    spread_kwargs_base.update(spread_line_kwargs or {})

    end_vals, end_colors = [], []
    for region in regions:
        d = row2_data[region]
        color = region_colors.get(region, 'k')
        sensor_dim = 'sensor' if 'sensor' in d['adj_std'].dims else None

        def _mean_abs_hpa(da):
            da = np.abs(da) / 100.
            return da.mean(sensor_dim) if sensor_dim else da

        std_vals = np.asarray(_mean_abs_hpa(d['adj_std']))
        spread_vals = np.asarray(_mean_abs_hpa(d['adj_spread']))

        ax.plot(time, std_vals, color=color, **std_kwargs_base)
        ax.plot(time, spread_vals, color=color, **spread_kwargs_base)

        end_vals.append(float(std_vals[-1]))
        end_colors.append(color)

    lo = -sigma_band_hpa
    bk = dict(color='0.5', alpha=0.3, edgecolor='none', label=SIGMA_BAND_LABEL, zorder=0)
    bk.update(band_kwargs or {})
    ax.fill_between(time, lo, sigma_band_hpa, **bk)

    pk = dict(color='k', label='P&D 2003 (SPNA)', zorder=1, **PD_LINE_STYLE)
    pk.update(pd_line_kwargs or {})
    ax.axhline(pd_rms_hpa, **pk)

    _style_time_axis(ax, time, yticks=yticks, ylim=ylim, tick_labelsize=tick_labelsize)

    # Direct end-of-line cable labels (axes-fraction x, data y so they sit
    # just past the right spine regardless of ylim) -- decluttered so they
    # don't collide where the 4 curves converge.
    label_ys = _declutter_1d(end_vals, min_label_gap)
    yaxis_transform = ax.get_yaxis_transform()
    for region, val, y, color in zip(regions, end_vals, label_ys, end_colors):
        if abs(y - val) > 1e-9:
            ax.plot([1.0, label_x - 0.005], [val, y], transform=yaxis_transform,
                    color=color, lw=0.8, clip_on=False, zorder=5)
        ax.annotate(
            region_labels[region], xy=(label_x, y), xycoords=('axes fraction', 'data'),
            color=color, fontsize=label_fontsize, fontweight='bold',
            va='center', ha='left', clip_on=False,
        )

    ax.set_ylabel(ylabel, fontsize=ylabel_fontsize)
    ax.tick_params(axis='y', labelsize=tick_labelsize)

    return ax


# =============================================================================
# Full-figure assembly -- a starting template, not a fixed API. Easiest to
# copy into a notebook and hack on directly once the panel content settles.
# =============================================================================

# (a)/(b) share one range/levels/colorbar now (both 0-3 hPa) so they're
# directly comparable at a glance -- ticks at every integer.
SIGMA_MAP_KWARGS = dict(levels=np.linspace(0, 3, 10), extend='max', robust=False)
SIGMA_MAP_CBAR_KWARGS = dict(ticks=[0, 1, 2, 3])


def make_fig9(
    ds,
    sigma_std_map=None,
    sigma_spread_map=None,
    sigma_spread=None,
    relcon_per_region=None,
    row2_data=None,
    figsize=(16, 13),
    cable_lonlat=None,
    landfacecolor='white',
):
    """Assemble the full 2x2 mosaic from already-loaded pieces: (a)/(b) maps
    on top, (c) combined timeseries + (d) grouped relcon bars on the bottom.

    Pass in sigma_std_map/sigma_spread_map/sigma_spread/relcon_per_region/
    row2_data explicitly (e.g. from the load_* functions above) rather than
    having this function load everything itself, so a notebook can load once
    and iterate on layout/styling quickly.

    sigma_std_map/sigma_spread_map (lat/lon, from gen_patm_uncertainty_fields.py
    via load_sigma_patm_std_map()/load_sigma_patm_spread_map()) drive panels
    (a)/(b), sharing one range/colorbar (SIGMA_MAP_KWARGS for levels/extend,
    SIGMA_MAP_CBAR_KWARGS for colorbar ticks) -- edit those module constants
    (not this function) to retune. sigma_spread (ASTE grid, from
    load_sigma_patm_spread()) is a separate load -- panel (c)'s grey band
    needs to index it at cable (tile, j, i) sensor locations, which the
    lat/lon map field can't do. relcon_per_region (from
    load_relcon_per_region()) drives panel (d)'s grouped bars.
    """
    sigma_std_map = sigma_std_map if sigma_std_map is not None else load_sigma_patm_std_map()
    sigma_spread_map = sigma_spread_map if sigma_spread_map is not None else load_sigma_patm_spread_map()
    sigma_spread = sigma_spread if sigma_spread is not None else load_sigma_patm_spread()
    relcon_per_region = relcon_per_region if relcon_per_region is not None else load_relcon_per_region()
    row2_data = row2_data if row2_data is not None else load_row2_data(ds, sigma_spread)

    if cable_lonlat is None:
        cable_lonlat = {r: (row2_data[r]['lons'], row2_data[r]['lats']) for r in REGIONS}

    # SPNA projection center, matching smartosse.plot.spna()'s defaults
    # (xmin=-80, xmax=10 -> central_longitude=-35; ymin=40, ymax=80 ->
    # central_latitude=60). Kept in sync by hand -- if spna()'s defaults
    # change, update here too.
    spna_proj = ccrs.LambertConformal(central_longitude=-35, central_latitude=60)

    fig = plt.figure(figsize=figsize)
    # 2 rows now (was 3: maps / per-cable timeseries / per-cable relcon) --
    # (c)/(d) replace the old 4+4 per-cable panels with one merged panel each.
    gs_outer = fig.add_gridspec(2, 1, height_ratios=[1.5, 1], hspace=0.3)

    # row 1: two maps, plain 1x2 split now that (g) is gone. wspace at 0 so
    # the two maps read as one wide comparison panel, not two separate ones
    # (some residual gap is inherent to cartopy's aspect-driven letterboxing
    # within each GeoAxes cell, not just the gridspec spacing -- closed below
    # via an explicit reposition once both maps are drawn).
    #
    # add_axes(rect) rather than add_subplot(subplotspec): axes made with
    # add_subplot stay tied to their SubplotSpec in this env's matplotlib
    # (3.4.3, pre Axes/Subplot unification) -- on every draw (incl. the
    # final savefig), SubplotBase.update_params() re-derives the "original"
    # box straight from the gridspec cell, silently undoing any manual
    # set_position() we do below. A plain add_axes() box has no subplotspec
    # to re-derive from, so a manual reposition sticks.
    gs_row1 = gs_outer[0].subgridspec(1, 2, wspace=0.0)
    rect_a = gs_row1[0, 0].get_position(fig).bounds
    rect_b = gs_row1[0, 1].get_position(fig).bounds
    row1_x0, _, row1_w, _ = gs_outer[0].get_position(fig).bounds
    row1_center = row1_x0 + row1_w / 2.  # full row-1 extent, i.e. same span row2/row3 sit in
    ax_a = fig.add_axes(rect_a, projection=spna_proj)
    ax_b = fig.add_axes(rect_b, projection=spna_proj)

    # decorate the map axes with spna()'s extent/land/gridlines (spna(ax=...)
    # applies its styling to an already-created GeoAxes rather than making a
    # new one, which is what lets this compose with the gridspec above).
    _, ax_a = spna(ax=ax_a, landfacecolor=landfacecolor)
    _, ax_b, gl_b = spna(ax=ax_b, landfacecolor=landfacecolor, return_gl=True)

    # (b) sits right next to (a) -- its own latitude labels would just
    # duplicate (a)'s, so hide them (longitude labels along the bottom stay).
    for label in gl_b[0]._labels:
        if 'N' in label.artist.get_text():
            label.artist.set_visible(False)

    # bottom row: (c) combined timeseries, (d) grouped relcon bars
    gs_row2 = gs_outer[1].subgridspec(1, 2, wspace=0.3)
    ax_c = fig.add_subplot(gs_row2[0, 0])
    ax_d = fig.add_subplot(gs_row2[0, 1])

    # (a)/(b) share one colorbar -- both add_colorbar=False here, one shared
    # horizontal colorbar built below from either mappable (same norm/levels).
    _, _, p_a = plot_sigma_patm_map(sigma_std_map, ax=ax_a, cable_lonlat=cable_lonlat,
                                     add_colorbar=False, **SIGMA_MAP_KWARGS)
    add_panel_label(ax_a, 'a', fontsize=60)

    plot_sigma_patm_map(sigma_spread_map, ax=ax_b, cable_lonlat=cable_lonlat,
                         add_colorbar=False, **SIGMA_MAP_KWARGS)
    add_panel_label(ax_b, 'b', fontsize=60)

    # gridspec wspace=0 above isn't enough on its own -- cartopy's set_extent
    # makes each GeoAxes shrink to its own aspect-correct box and *center*
    # that box within its allocated cell, so a visible gap remains on both
    # sides of the cell boundary even at wspace=0. Fix it directly: once
    # both maps are drawn (forcing that shrink to resolve), glue them
    # together and re-center *the pair* on row1's full extent (matching
    # row2/row3's center) rather than sliding (b) next to (a)'s own natural
    # position -- (a) alone is centered only within its half of row1, which
    # is *not* row1's overall center, so that naive glue left the whole
    # (a)+(b) block visibly off-center vs. rows 2/3 below. Setting position
    # with which='both' (the default) makes this the new *original* box too,
    # so the aspect machinery doesn't re-center it away on the next
    # draw/save.
    fig.canvas.draw()
    pos_a, pos_b = ax_a.get_position(), ax_b.get_position()
    map_gap = 0.005
    combined_width = pos_a.width + map_gap + pos_b.width
    new_x0 = row1_center - combined_width / 2.
    ax_a.set_position([new_x0, pos_a.y0, pos_a.width, pos_a.height])
    ax_b.set_position([new_x0 + pos_a.width + map_gap, pos_b.y0, pos_b.width, pos_b.height])

    # Build the shared colorbar via a manually-placed `cax` rather than
    # fig.colorbar(..., ax=[ax_a, ax_b]) -- the latter's automatic
    # space-stealing resize of its parent axes silently undid the sizing/
    # centering fix above (it shrank ax_a/ax_b well below the width just
    # computed, whether done before or after the fix). A manual cax, sized
    # relative to the now-final (pos_a, pos_b), can't feed back on them.
    cbar_width = 0.6 * combined_width   # matches the old shrink=0.6 fraction
    cbar_height = 0.015
    cbar_pad = 0.03
    cax = fig.add_axes([
        row1_center - cbar_width / 2., pos_a.y0 - cbar_pad - cbar_height,
        cbar_width, cbar_height,
    ])
    cbar_ab = fig.colorbar(p_a, cax=cax, orientation='horizontal', **SIGMA_MAP_CBAR_KWARGS)
    cbar_ab.ax.set_xlabel('[hPa]', fontsize=22, labelpad=2)  # nudged up (toward the colorbar) from mpl's default labelpad=4
    cbar_ab.ax.tick_params(labelsize=20)

    plot_patm_adjustment_combined(ax_c, row2_data, ylim=(-1, 3), label_fontsize=18, min_label_gap=0.3)
    add_panel_label(ax_c, 'c', fontsize=26, x=0.02, y=0.95)
    # bbox_to_anchor y nudged below the panel-label letter (y=0.95, ~0.87 or
    # lower for its own box height) so the two don't overlap -- they used to
    # sit on top of each other at plain loc='upper left'.
    ax_c.legend(handles=_row2_legend_handles(), fontsize=13, frameon=False,
                loc='upper left', bbox_to_anchor=(0.0, 0.87))

    plot_relcon_bars_grouped(ax_d, relcon_per_region, tick_fontsize=14, ylabel_fontsize=18)
    add_panel_label(ax_d, 'd', fontsize=26, x=0.02, y=0.95)
    shade_legend = ax_d.legend(handles=_relcon_shade_legend_handles(), fontsize=12, frameon=False,
                                loc='upper left', bbox_to_anchor=(1.02, 1.0), title='component',
                                title_fontsize=12)
    ax_d.add_artist(shade_legend)
    ax_d.legend(handles=_relcon_hatch_legend_handles(), fontsize=12, frameon=False,
                loc='upper left', bbox_to_anchor=(1.02, 0.55), title='run', title_fontsize=12)

    return fig, dict(a=ax_a, b=ax_b, c=ax_c, d=ax_d)
